[package]
name = "intro-to-rust"
version = "0.1.0"
authors = ["Taylor Fraley <taylor.o.fraley@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
